using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics.Internal;
using Tetrio.Foxhole.Database;
using Tetrio.Foxhole.Database.Enums;
using Tetrio.Foxhole.Network.Api.Tetrio;

namespace Tetrio.Zenith.DailyChallenge.ChallengeGeneration;

public abstract class BaseChallengeGenerator
{
    protected Random _random;
    protected DateTime _day;

    public BaseChallengeGenerator(Random random, DateTime day)
    {
        _random = random;
        _day = day;
    }

    protected bool Chance(double probability)
    {
        if (probability <= 0) return false;
        if (probability >= 1) return true;
        return _random.NextDouble() < probability; // probability01 in [0..1]
    }

    protected List<ConditionType> GetRandomConditions(Mods[] mods)
    {
        var allConditions = Enum.GetValues<ConditionType>().ToList();

        allConditions.RemoveAt(0);
        // Removed finesse for challenge generator because of popular request
        allConditions.Remove(ConditionType.Finesse);
        allConditions.Remove(ConditionType.Lines); // Removed because it will be automatically generated by chance
        allConditions.Remove(ConditionType.TotalBonus); // Removed for now as balancing is not done yet
        allConditions.Remove(ConditionType.App);        // Temporally removed because of calculation missing

        // If no hold was selected as mod, remove all clears from the condition roll
        if(mods.Contains(Mods.NoHold)) allConditions.Remove(ConditionType.AllClears);

        allConditions = allConditions.OrderBy(_ => _random.Next()).ToList();

        var selectedConditions = allConditions.Take(_random.Next(2, 4)).ToList();

        return selectedConditions;
    }

    protected List<ConditionType> GetRandomConditionsWithoutAllClears()
    {
        var allConditions = Enum.GetValues<ConditionType>().ToList();

        allConditions.RemoveAt(0);
        allConditions.Remove(ConditionType.Finesse);

        allConditions.Remove(ConditionType.AllClears);

        allConditions = allConditions.OrderBy(_ => _random.Next()).ToList();

        var selectedConditions = allConditions.Take(_random.Next(1, 3)).ToList();

        return selectedConditions;
    }

    protected async Task<(double min, double max)> GetRangeForConditionAndDifficulty(TetrioContext context, ConditionType condition, Difficulty difficulty)
    {
        var range = await context.ConditionRanges.FirstOrDefaultAsync(x => x.ConditionType == condition && x.Difficulty == difficulty);

        if(range == null)
            return (0, 0);

        return (range.Min, range.Max);
    }

    protected async Task<double> CalculateScalingFactors(ConditionType type, Mods[] mods)
    {
        if(type == ConditionType.Height) return await CalculateAltitudeScaling(mods);

        var scaling = 1d;

        // Types to ignore, because they have no scaling
        if (type is ConditionType.KOs
            or ConditionType.AllClears
            or ConditionType.Finesse
            or ConditionType.Special
            or ConditionType.TotalBonus
            or ConditionType.Lines) return scaling;

        foreach (var mod in mods)
        {
            scaling *= Math.Round(mod switch
            {
                Mods.NoMod => 1d,
                Mods.Expert => 1d,
                Mods.NoHold => Scaling.NoHoldScaling[type],
                Mods.Messy => Scaling.MessyScaling[type],
                Mods.Gravity => Scaling.GravityScaling[type],
                Mods.Volatile => Scaling.VolatileScaling[type],
                Mods.DoubleHole => Scaling.DoubleHoleScaling[type],
                Mods.Invisible => Scaling.InvisibleScaling[type],
                Mods.AllSpin => Scaling.AllSpinScaling[type],
                _ => 1d
            }, 3);
        }

        Console.WriteLine($"\t- Scaling factor for {type} is {scaling}");

        return scaling;
    }

    private async Task<double> CalculateAltitudeScaling(Mods[] mods)
    {
        // Scaling is based on the world record of a mod and nomod world record

        var scaling = 1d;

        // When there are mods, we don't need to apply any scaling for altitude
        if (mods.Length == 0 || mods.All(m => m == Mods.NoMod)) return scaling;

        var noModRecord = await GetWorldRecordOfMod(Mods.NoMod);

        Console.WriteLine($"\t- NoMod WR: {noModRecord}");

        foreach (var mod in mods)
        {
            var modRecord = await GetWorldRecordOfMod(mod);

            Console.WriteLine($"\t- {mod} WR: {modRecord}");

            // Apply multiplicative scaling
            // Formular: [Mod WR] / [Zenith Explorer WR] * 0.25 + 0.75
            scaling *= modRecord / noModRecord * 0.25 + 0.75;
        }

        Console.WriteLine($"\t- Scaling factor for Altitude is {scaling}");

        return scaling;
    }

    protected async Task<double> GetWorldRecordOfMod(Mods? mod = null)
    {
        var tetrioApi = new TetrioApi();

        var achievementId = mod switch
        {
            Mods.NoMod => ModAchievements.NoMod,
            Mods.Expert => ModAchievements.Expert,
            Mods.NoHold => ModAchievements.NoHold,
            Mods.Messy => ModAchievements.Messy,
            Mods.Gravity => ModAchievements.Gravity,
            Mods.Volatile => ModAchievements.Volatile,
            Mods.DoubleHole => ModAchievements.DoubleHole,
            Mods.Invisible => ModAchievements.Invisible,
            Mods.AllSpin => ModAchievements.AllSpin,
            _ => ModAchievements.NoMod
        };

        var achievementData = await tetrioApi.GetAchievement(achievementId);

        return achievementData?.Leaderboard?.OrderByDescending(x => x.Value).FirstOrDefault()?.Value ?? -1;
    }
}